version: "3.9"
services:
  timescale:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netmon
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netmon"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7
    ports: ["6379:6379"]

  grafana:
    image: grafana/grafana:10.4.6
    ports: ["3000:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards